-- MySQL Script generated by MySQL Workbench
-- Sat Nov 14 03:46:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
--
-- -- -----------------------------------------------------
-- -- Schema mydb
-- -- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS mydb ;
--
-- -- -----------------------------------------------------
-- -- Schema mydb
-- -- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8 ;
-- USE mydb ;

-- -----------------------------------------------------
-- Table mydb.`company`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS company ;

CREATE TABLE IF NOT EXISTS company (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  tax_number VARCHAR(20) NOT NULL,
  authorized_capital DOUBLE NOT NULL,
  field_of_operation VARCHAR(100) NOT NULL,
  address_in_building VARCHAR(20) NOT NULL,
  phone_number VARCHAR(10) NOT NULL,
  ground_area INT NOT NULL,
  PRIMARY KEY (id));
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.`employee_company`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS employee_company ;

CREATE TABLE IF NOT EXISTS employee_company (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  employee_company_code VARCHAR(20) NOT NULL,
  id_card VARCHAR(20) NOT NULL,
  date_of_birth DATE NOT NULL,
  phone_number VARCHAR(10) NOT NULL,
  company_id INT NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_employee_company_company1_idx (company_id ASC) VISIBLE,
  CONSTRAINT fk_employee_company_company1
    FOREIGN KEY (company_id)
    REFERENCES company (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.`service`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS service ;

CREATE TABLE IF NOT EXISTS service (
  id INT NOT NULL AUTO_INCREMENT,
  service_code VARCHAR(20) NOT NULL,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(20) NOT NULL,
  unit_price DOUBLE NOT NULL,
  PRIMARY KEY (id));
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.`staff`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS staff ;

CREATE TABLE IF NOT EXISTS staff(
  id INT NOT NULL AUTO_INCREMENT,
  staff_code VARCHAR(20) NOT NULL,
  name VARCHAR(100) NOT NULL,
  date_of_birth DATE NOT NULL,
  address VARCHAR(100) NOT NULL,
  phone_number VARCHAR(10) NOT NULL,
  PRIMARY KEY (id));
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.`account`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS account ;
--
-- CREATE TABLE IF NOT EXISTS account (
--   id INT NOT NULL AUTO_INCREMENT,
--   username VARCHAR(45) NOT NULL,
--   password VARCHAR(45) NOT NULL,
--   employee_id INT NOT NULL,
--   PRIMARY KEY (id),
--   INDEX fk_account_employee_idx (employee_id ASC) VISIBLE,
--   CONSTRAINT fk_account_employee
--     FOREIGN KEY (employee_id)
--     REFERENCES staff (id)
--     ON DELETE CASCADE
--     ON UPDATE CASCADE);
-- -- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.`company_service`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS company_service ;

CREATE TABLE IF NOT EXISTS company_service(
  id INT NOT NULL AUTO_INCREMENT,
  service_id INT NOT NULL,
  company_id INT NOT NULL,
  month INT NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_company_service_service1_idx (service_id ASC) VISIBLE,
  INDEX fk_company_service_company1_idx (company_id ASC) VISIBLE,
  CONSTRAINT fk_company_service_service1
    FOREIGN KEY (service_id)
    REFERENCES service (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_company_service_company1
    FOREIGN KEY (company_id)
    REFERENCES company (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS staff_service(
    id INT NOT NULL AUTO_INCREMENT,
  service_id INT NOT NULL,
  staff_id INT NOT NULL,
  salary DOUBLE NOT NULL,
  position VARCHAR (20) NOT NULL,
  level VARCHAR(20) NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_staff_service_service1_idx (service_id ASC) VISIBLE,
  INDEX fk_staff_service_company1_idx (staff_id ASC) VISIBLE,
  CONSTRAINT fk_staff_service_service1
    FOREIGN KEY (service_id)
    REFERENCES service (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_staff_service_company1
    FOREIGN KEY (staff_id)
    REFERENCES staff (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
-- ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;